### ISSUE TITLE
XDG_CONFIG_HOME is not appropriate for headless installs

### ISSUE THREAD

**Issue by nightpool** [skircheis/xapblr#3]
e.g. an ubuntu box without X installed will not have XDG_CONFIG_HOME set.

```
nightpool@fendant2:~/xapblr$ xapblr index nightpool
Traceback (most recent call last):
  File "/usr/local/bin/xapblr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xapblr/__init__.py", line 6, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/xapblr/index.py", line 106, in index
    api_key = get_api_key()
  File "/usr/local/lib/python3.10/dist-packages/xapblr/utils.py", line 27, in get_api_key
    xdg_config_home = Path(environ["XDG_CONFIG_HOME"])
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_CONFIG_HOME'
```

**Comment by nightpool** [comment]
I guess this is why the xapblr@.service file exists.

**Comment by skircheis** [comment]
This should be fixed in 8f052f2f1aa5cac55f21c05cd69e81e792bde33f.

> I guess this is why the [xapblr@.service](mailto:xapblr@.service) file exists.

Ah, that's because systemd doesn't pass environment variables.
