### ISSUE TITLE
updating get_latest during indexing isn't error-safe

### ISSUE THREAD

**Issue by nightpool** [skircheis/xapblr#4]
After running into an error during the initial indexing:
```
(.venv) nightpool@fendant2:~/xapblr$ PYTHONPATH=src python -m xapblr index nightpool
Indexing nightpool... Database is empty, indexing until beginning...
ETA: in 39 minutes and 46.8 seconds (Sun Aug  6 12:25:56 2023)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/nightpool/xapblr/src/xapblr/__main__.py", line 3, in <module>
    main()
  File "/home/nightpool/xapblr/src/xapblr/__init__.py", line 6, in main
    args.func(args)
  File "/home/nightpool/xapblr/src/xapblr/index.py", line 169, in index
    (id_term, post_doc) = index_post(p, tg)
  File "/home/nightpool/xapblr/src/xapblr/index.py", line 94, in index_post
    doc.add_term(encode_tag(t))
  File "/home/nightpool/xapblr/src/xapblr/utils.py", line 68, in encode_tag
    return (prefixes["tag"] + urlencode(tag.lower()))[:245]
NameError: name 'urlencode' is not defined
```

xapblr would refuse to index any more posts until I cleared the db
```
(.venv) nightpool@fendant2:~/xapblr$ PYTHONPATH=src python -m xapblr index nightpool
Indexing nightpool... Latest seen post is 2 hours, 33 minutes and 34.64 seconds ago...
No new posts since 2 hours, 33 minutes and 34.97 seconds ago
Done; indexed 0 posts.
```

while this error state was pretty easy to recover from (just rm -r the whole db directory), it would be a lot more dangerous if I already had a pretty extensive database and indexing errored out on e.g. a tag. 

It seems like this issue is because we index from newest-to-oldest and then start from the newest document instead of the oldest. Instead, we should flip the indexing logic so that we always insert documents from oldest to newest.

**Comment by skircheis** [comment]
The API doesn't let us access posts from oldest to newest. You can get around this by passing `--full` to force xapblr to continue back to the beginning of the blog.
